import { Component, computed, signal } from '@angular/core';
import { DailyTimeSlotEditorComponent } from '../daily-time-slot-editor/daily-time-slot-editor.component';
import {
  ITimeFrameAvailabilityTemplate,
  ITimeSlot,
} from '../../interfaces/time-slot';

@Component({
  selector: 'app-availability-editor',
  imports: [DailyTimeSlotEditorComponent],
  templateUrl: './availability-editor.component.html',
  styleUrl: './availability-editor.component.scss',
})
export class AvailabilityEditorComponent {
  days = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
  ];

  timeFrameAvailability = signal<ITimeFrameAvailabilityTemplate>({
    name: 'Default template',
    description: 'Autogenerated template for availability',
    dailyAvailabilities: this.days.map((day, index) => ({
      dayIndex: index,
      timeSlots: [],
      isAvailable: true,
      isVisible: true,
      isEditable: true,
    })),
  });

  showUnavailableDays = signal<boolean>(false);

  dailyAvailabilities = computed(() => {
    return this.timeFrameAvailability().dailyAvailabilities;
  });

  countAvailableDays = computed(() => {
    return this.showUnavailableDays() ? 7 : this.dailyAvailabilities().filter((availability) => availability.isAvailable).length;
  });

  onTimeSlotChanged(changedDayTimeSlots: ITimeSlot[], dayIndex: number) {
    this.timeFrameAvailability.update((old) => {
      return {
        ...old,
        dailyAvailabilities: old.dailyAvailabilities.map(
          (availability, index) =>
            index === dayIndex
              ? { ...availability, timeSlots: changedDayTimeSlots }
              : availability
        ),
      };
    });
  }
  onAvailabilityChanged($event: boolean, dayIndex: number) {
    this.timeFrameAvailability.update((old) => {
      return {
        ...old,
        dailyAvailabilities: old.dailyAvailabilities.map(
          (availability, index) =>
            index === dayIndex ? { ...availability, isAvailable: $event } : availability
        ),
      };
    });
  }
}
